### PR TITLE
Add: Sidebar & Footer

### PR DESCRIPTION
**Pull request by MonarthS**
- Responsive Header
- Responsive Chart

### CODE REVIEW

**Comment by MonarthS** [comment]
@100sarthak100 You have to add the "**hacktoberfest**" topic to the repository to participate.

**Comment by 100sarthak100** [comment]
I have added the 'Hacktoberfest' in the tag of the repo.

**Comment by MonarthS** [comment]
image
Checkout this, as per this guid-line, you have to add it on repo topic.

**Comment by 100sarthak100** [comment]
wait, I'll fix the issue.

**Comment by 100sarthak100** [comment]
Can you share more info, as where the tag should be added, in the repo name, or somewhere else?

**Comment by 100sarthak100** [comment]
> Can you share more info, as where the tag should be added, in the repo name, or somewhere else?

Got it, the issue will be fixed shortly.

**Comment by 100sarthak100** [comment]
Check if it works now. I have added the topic and the tag name.

**Review by 100sarthak100 — CHANGES_REQUESTED** [review]
The sidebar fits good, but the Chart x-axis data is getting hide behind the footer, also when removing the footer the x-axis is still not visible.
check

This must be a common position issue, after this, I'll approve the PR.

**Comment by 100sarthak100** [comment]
I think I got it, remove the  `fix` className in App.js file and it will work fine.

**Comment by 100sarthak100** [comment]
Also, can you make the sidebar of dark grey color?

**Comment by 100sarthak100** [comment]
> Also, can you make the sidebar of dark grey color?

And footer also, with the text color as white.

**Comment by MonarthS** [comment]
Okay I'll check it.

**Comment by MonarthS** [comment]
> Also, can you make the sidebar of dark grey color?

Dark grey like header?



> > Also, can you make the sidebar of dark grey color?
> 
> And footer also, with the text color as white.

With same background color as header?

**Comment by 100sarthak100** [comment]
> > Also, can you make the sidebar of dark grey color?
> 
> Dark grey like header?
> 
> > > Also, can you make the sidebar of dark grey color?
> > 
> > 
> > And footer also, with the text color as white.
> 
> With same background color as header?

Yeah

**Comment by 100sarthak100** [comment]
> > > Also, can you make the sidebar of dark grey color?
> > 
> > 
> > Dark grey like header?
> > > > Also, can you make the sidebar of dark grey color?
> > > 
> > > 
> > > And footer also, with the text color as white.
> > 
> > 
> > With same background color as header?
> 
> Yeah

And the text color as white

**Comment by MonarthS** [comment]
@100sarthak100 Changed sidebar & footer background.

**Review by 100sarthak100 — APPROVED** [review]
Thank you for contributing. Your PR is approved. hacktoberfest-accepted.

**Pull request merged**
